### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by kinchan-tokyo** [kinchan-tokyo/test2#1]
- a
- i

## ttt

- [x] i

**Comment by kinchan-tokyo** [comment]
- aaa
![image](https://user-images.githubusercontent.com/56061395/66300391-29c52a00-e930-11e9-82e1-dedbd57956c3.png)

**Comment by kinchan-tokyo** [comment]
猫

**Comment by simiraaaa** [comment]
https://github.com/kinchan-tokyo/test2/commit/41cf09ade48416a432b0e485cc198ebac32aca0d
終わった

**Comment by simiraaaa** [comment]
確認したらclose

**Comment by kinchan-tokyo** [comment]
@simiraaaa ok
